### ISSUE TITLE
CUDA out of memory when running unit tests

### ISSUE THREAD

**Issue by sarthakpati** [mlcommons/GaNDLF#484]
**Describe the bug**
When trying to run the unit tests (or even a subset), CUDA OOM error occurs.

**To Reproduce**
```powershell
# follow setup instructions in https://cbica.github.io/GaNDLF/setup
conda activate venv_gandlf
# export CUDA_VISIBLE_DEVICES to the GPU device you want to run the test on
pytest --device cuda --cov=. --cov-report=xml --cov-append -k "regression_rad_2d_imagenet"
# see error
FAILED testing/test_full.py::test_train_regression_rad_2d_imagenet - RuntimeError: CUDA out of memory. Tried to allocate 392.00 MiB (GPU 0; 8.00 GiB total capacity; 6.88 GiB already allocated; 0 bytes free; 6.97 GiB reserved in total by PyTorch)
```

**Expected behavior**
The memory between multiple invocations to the `TrainingManager` should get cleaned properly, which is apparently not happening right now.

**Screenshots**
N.A.

**GaNDLF Version**

0.0.15-dev

**Desktop (please complete the following information):**
 - OS: N.A.
 - Version: N.A.

**Additional context**
- [failures.log](https://github.com/CBICA/GaNDLF/files/9481447/failures.log) attached for reference.
- I am seeing CUDA memory usage increasing with every iteration of the loop at https://github.com/CBICA/GaNDLF/blob/5030ff83a38947c1583b58a08598308886ee9a0a/testing/test_full.py#L347 
- I am seeing this error on this specific test because the machine I am running it on as 8G VRAM, but this would be different on another machine, where we might need to try with a larger model/test to trigger this error.

**Comment by AlexanderGetka-cbica** [comment]
I want you to know that I am looking into this. Perhaps there is an easy workaround.
However, we should all be keeping an eye on things like this, since knowledge about how to make this work (really, on wrangling the python runtime environment in general) is useful across projects. 

Side note: I have a talk on this sort of topic that I am working on. Right now it's mostly about multithreading pitfalls, but if there's any other problem patterns like this you've learned to avoid (that extend to Python in general, or Python specifically for ML/DL), please let me know so I can include that ( and credit you, of course :) ).
