### ISSUE TITLE
[BUG] SimpleITK version 2.3.0 causes errors

### ISSUE THREAD

**Issue by Linardos** [mlcommons/GaNDLF#894]
### Describe the bug
There is an issue with running the Fets Challenge pertaining to SimpleITK.
![image](https://github.com/mlcommons/GaNDLF/assets/26694607/f339d26b-88c7-4751-93f4-2c76aab325d4)

### To Reproduce
1. Data used is that of FeTS challenges 2022 and 2024 (https://www.synapse.org/Synapse:syn29264504)
2. To reproduce the behavior, follow the instructions: https://github.com/FeTS-AI/Challenge/tree/main/Task_1

### Environment information

This happened both in WSL and in a VirtualBox Linux environment
GaNDLF version according to pip freeze gives me this:
GANDLF @ git+https://github.com/CBICA/GaNDLF.git@e4d0d4bfdf4076130817001a98dfb90189956278

### Solution:
The issue was caused by SimpleITK 2.3.0. I tried and it works if I install simpleITK version 2.2.0 or 2.2.1

**Comment by sarthakpati** [comment]
Hmm, the latest CI runs (<3 months) seem to be using 2.3.1, and all are running without issue. I was unable to replicate this issue on 2 of my WSL systems or on my local machine. Is it possible that this was because some underlying system library was missing? I am unsure how to proceed. Any ideas?

**Comment by sarthakpati** [comment]
Can you check if you are seeing the same issues with [SimpleITK 2.4.0](https://github.com/SimpleITK/SimpleITK/releases/tag/v2.4.0) as well?

**Comment by sarthakpati** [comment]
This seems to be related to the underlying system GLIB version. The best way to handle this would be to update it, unless the SimpleITK folks can say something otherwise on their forum. Another potential solution is explained on this thread: https://github.com/ContinuumIO/anaconda-issues/issues/7640

I am closing this thread out, please re-open or create a new issue if you run into anything else.
